// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type Player struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Level     int32     `json:"level"`
	Class     string    `json:"class"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
